apiVersion: v1
kind: ConfigMap
metadata:
  name: go-app-config
  namespace: production
data:
  PORT: "8080"
  DB_HOST: "postgress-cluster-rw.production-db.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "app"
  DB_USER: "app"