apiVersion: v1
kind: Secret
metadata:
  name: go-app-secrets
  namespace: production
type: Opaque
data:
  IPSTACK_API_KEY: "eW91ci1pcHN0YWNrLWFwaS1rZXk=" 
  DB_PASSWORD: "Nmc3YnpnWXVwZjZHc1NsT0dDbk40SWxOZWRScEtFU1RzRmN5YmZCd2JMYVQwYWxNMXUwMU9oRnNEMUl1NXppVg=="  

---
apiVersion: v1
kind: Secret
metadata:
  name: aria-registry-secret
  namespace: production
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS0xNzI1MDI1MmJjLWFyaWEuYXBwcy5pci1jZW50cmFsMS5hcnZhbmNhYXMuaXIiOnsidXNlcm5hbWUiOiJhcmlhIiwicGFzc3dvcmQiOiIxMjM0NTY3OCIsImF1dGgiOiJZWEpwWVRveE1qTTBOVFkzT0E9PSJ9fX0=