apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-app.fullname" . }}-config
  labels:
    {{- include "go-app.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  DB_HOST: {{ .Values.config.database.host | quote }}
  DB_PORT: {{ .Values.config.database.port | quote }}
  DB_NAME: {{ .Values.config.database.name | quote }}
  DB_USER: {{ .Values.config.database.user | quote }}